name: CI
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  flake-check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
  tests:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - run: "nix develop -c echo preparing environment"
      - run: "set -o pipefail; nix develop -c bats test/{test,long_tests}.bats | tee tests.tap"
      - uses: pcolby/tap-summary@v1
        if: always()
